spring:
  profiles:
    active:
      - testall
    group:
      prodall:
        - prod
        - prodmq
        - proddb
      devall:
        - dev
        - devdb
        - devmq
      testall:
        - test
        - testdb
        - testmq
---
spring.config.activate.on-profile: dev

env: dev

server:
  port: 8080

---
spring.config.activate.on-profile: devdb

db:
  name: mysql_dev

env: devdb

---
spring.config.activate.on-profile: devmq

mq:
  address: mq_dev

env: devmq

---
spring.config.activate.on-profile: test

env: test

server:
  port: 8081
---
spring.config.activate.on-profile: testdb

db:
  name: mysql_test

env: testdb

---
spring.config.activate.on-profile: testmq

mq:
  address: mq_test

env: testmq

---
spring.config.activate.on-profile: prod

env: prod

server:
  port: 8082

---
spring.config.activate.on-profile: proddb

db:
  name: mysql_prod

env: proddb

---
spring.config.activate.on-profile: prodmq

mq:
  address: mq_prod

env: prodmq