spring:
  profiles:
    active: standalone

---
spring:
  profiles: standalone
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
        shutdown-timeout: 100ms
---
spring:
  profiles: sentinel
  redis:
    password: redis
    sentinel:
      master: mymaster
      nodes:
        - 192.168.11.163:26379
        - 192.168.11.164:26379
        - 192.168.11.165:26379
